name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies for linting
        run: |
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint --strict --format colored .

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: "5.4.2"

      - name: Validate cluster manifests
        run: |
          kustomize build clusters/dev/cluster-a
          kustomize build clusters/prod/cluster-b

      - name: Build Docker image
        run: |
          docker build -t spider-api:ci apps/tenants/spider-api

      - name: Run deployment smoke test
        run: |
          set -euo pipefail
          docker run -d --rm --name spider-api-ci -p 8080:8080 spider-api:ci
          trap "docker rm -f spider-api-ci" EXIT
          for i in {1..30}; do
            if curl --fail --silent http://localhost:8080/healthz > /dev/null; then
              break
            fi
            sleep 1
          done
          curl --fail --silent http://localhost:8080/healthz
